services:
  backend:
    # imagen en Docker Hub
    image: diegomez27/save-backend-v2:2.0.0 
    restart: always
    ports:
      - "${PORT:-3001}:3001"
    environment:
      - DB_HOST=savedb
      - DB_PORT=5432
      - DB_USERNAME=${DB_USERNAME:-postgres}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE:-SaveDB}
      - JWT_SECRET=${JWT_SECRET:}
      - NODE_ENV=development # cambiar a 'production' cuando tenga migraciones
    depends_on:
      db:
        condition: service_healthy
    networks:
      - save-network

  db:
    image: postgres:17.2
    restart: always
    container_name: savedb
    ports:
      - "${DB_PORT:-5434}:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE:-SaveDB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - save-network

volumes:
  postgres_data:

networks:
  save-network:
    driver: bridge