services:
  # --- Frontend (Nginx + Ionic) ---
  frontend:
    image: diegomez27/save-frontend:1.0.0
    restart: always
    ports:
      - "80:80" # El usuario entra por aqu√≠ (http://localhost)
    depends_on:
      - backend
    networks:
      - save-network

  # --- Backend (NestJS) ---
  backend:
    image: diegomez27/save-backend-v2
    restart: always
    ports:
      - "${PORT:-3001}:3001"
    environment:
      - DB_HOST=savedb
      - DB_PORT=5432
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - JWT_SECRET=${JWT_SECRET}
      - NODE_ENV=development
    depends_on:
      db:
        condition: service_healthy
    networks:
      - save-network

  # --- Base de Datos (PostgreSQL) ---
  db:
    image: postgres:17.2
    restart: always
    container_name: savedb
    ports:
      - "${DB_PORT:-5434}:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - save-network

volumes:
  postgres_data:

networks:
  save-network:
    driver: bridge